name: Build docker image

on:
  push:
    branches:
      - "*"
env:
  REGISTRY: docker.io

jobs:
  linuxarm64build:
    name: build xray-ui arm64 version
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up Go
        uses: actions/setup-go@v4.0.0
        with:
          go-version: "stable"
      - name: build linux arm64 version
        run: |
          sudo apt-get update
          sudo apt install gcc-aarch64-linux-gnu
          CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build -o xray-release -ldflags '-linkmode "external" -extldflags "-static"' -v main.go
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: docker.io/juestnow/xray-ui
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Login to dokcer Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push amd64
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          file: .github/docker/Dockerfile-amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push arm64
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          file: .github/docker/Dockerfile-arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}